-- Esegui tutto questo file nel "SQL Editor" di Supabase.
create table if not exists public.photos (
  id uuid primary key default gen_random_uuid(),
  event_name text not null,
  event_date date not null,
  event_code text not null,
  storage_path text not null unique,
  download_count bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.photos
add column if not exists event_code text
default replace(gen_random_uuid()::text, '-', '');
alter table public.photos
add column if not exists download_count bigint not null default 0;

update public.photos
set event_code = replace(gen_random_uuid()::text, '-', '')
where event_code is null;

alter table public.photos alter column event_code set not null;
create index if not exists photos_event_code_idx on public.photos(event_code);

create table if not exists public.admin_settings (
  id smallint primary key default 1 check (id = 1),
  username text not null,
  email text not null,
  password_hash bytea not null,
  updated_at timestamptz not null default now()
);

alter table public.admin_settings add column if not exists username text;
alter table public.admin_settings add column if not exists email text;
alter table public.admin_settings add column if not exists password_hash bytea;
alter table public.admin_settings enable row level security;
revoke all on table public.admin_settings from anon, authenticated;

create or replace function public.is_admin_request()
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  request_headers jsonb;
  supplied_identifier text;
  supplied_password text;
begin
  request_headers := coalesce(
    nullif(current_setting('request.headers', true), ''),
    '{}'
  )::jsonb;
  supplied_identifier := lower(trim(coalesce(request_headers ->> 'x-polaroid-admin-identifier', '')));
  supplied_password := coalesce(request_headers ->> 'x-polaroid-admin-password', '');

  return exists (
    select 1
    from public.admin_settings
    where id = 1
      and supplied_identifier in (lower(username), lower(email))
      and password_hash = extensions.digest(supplied_password, 'sha256')
  );
exception when others then
  return false;
end;
$$;

revoke all on function public.is_admin_request() from public;
grant execute on function public.is_admin_request() to anon, authenticated;

create or replace function public.increment_photo_download(
  target_photo_id uuid,
  target_event_code text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  update public.photos
  set download_count = download_count + 1
  where id = target_photo_id
    and event_code = target_event_code
  returning download_count into new_count;

  return new_count;
end;
$$;

revoke all on function public.increment_photo_download(uuid, text) from public;
grant execute on function public.increment_photo_download(uuid, text) to anon, authenticated;

create table if not exists public.event_visits (
  id bigint generated by default as identity primary key,
  event_code text not null,
  visitor_key uuid not null,
  first_seen_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conrelid = 'public.event_visits'::regclass
      and conname = 'event_visits_pkey'
      and pg_get_constraintdef(oid) like '%event_code%visitor_key%'
  ) then
    alter table public.event_visits drop constraint event_visits_pkey;
  end if;
end;
$$;

alter table public.event_visits
add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.event_visits'::regclass
      and contype = 'p'
  ) then
    alter table public.event_visits add primary key (id);
  end if;
end;
$$;

alter table public.event_visits enable row level security;
revoke all on table public.event_visits from anon, authenticated;

create or replace function public.record_gallery_visit(
  target_event_code text,
  target_visitor_key uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.photos where event_code = target_event_code
  ) then
    return false;
  end if;

  insert into public.event_visits (event_code, visitor_key)
  values (target_event_code, target_visitor_key);

  return true;
end;
$$;

revoke all on function public.record_gallery_visit(text, uuid) from public;
grant execute on function public.record_gallery_visit(text, uuid) to anon, authenticated;

create or replace function public.get_admin_gallery_stats()
returns table (total_visitors bigint, total_downloads bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin_request() then
    return query select 0::bigint, 0::bigint;
    return;
  end if;

  return query
  select
    (select count(*)::bigint from public.event_visits),
    (select coalesce(sum(download_count), 0)::bigint from public.photos);
end;
$$;

revoke all on function public.get_admin_gallery_stats() from public;
grant execute on function public.get_admin_gallery_stats() to anon, authenticated;

alter table public.photos enable row level security;

drop policy if exists "Tutti possono vedere le foto" on public.photos;
create policy "Tutti possono vedere le foto"
on public.photos for select using (true);

drop policy if exists "Solo admin autenticato inserisce foto" on public.photos;
create policy "Solo admin autenticato inserisce foto"
on public.photos for insert
with check (public.is_admin_request());

drop policy if exists "Solo admin autenticato elimina foto" on public.photos;
create policy "Solo admin autenticato elimina foto"
on public.photos for delete
using (public.is_admin_request());

insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do update set public = true;

drop policy if exists "Tutti possono visualizzare i file" on storage.objects;
create policy "Tutti possono visualizzare i file"
on storage.objects for select using (bucket_id = 'photos');

drop policy if exists "Solo admin carica i file" on storage.objects;
create policy "Solo admin carica i file"
on storage.objects for insert
with check (
  bucket_id = 'photos'
  and public.is_admin_request()
);

drop policy if exists "Solo admin elimina i file" on storage.objects;
create policy "Solo admin elimina i file"
on storage.objects for delete
using (
  bucket_id = 'photos'
  and public.is_admin_request()
);

-- Nome utente, e-mail e hash della password vanno inseriti nella tabella
-- admin_settings dal pannello Supabase, senza pubblicare la password in questo file.
